spring.application.name=1_init
server.port=8081
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.url=jdbc:h2:mem:dbduplicata
spring.datasource.username=sa
spring.datasource.password=sa

spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.show-sql=true
#spring.jpa.properties.hibernate.format_sql=true
spring.jpa.hibernate.ddl-auto=create

spring.security.oauth2.client.registration.keycloak.client-id=client-spring
spring.security.oauth2.client.registration.keycloak.client-secret=vJMzmwxqSNq4SM7BzQix4yIBCKyjXDDe
spring.security.oauth2.client.registration.keycloak.scope=openid,profile,email
spring.security.oauth2.client.registration.keycloak.authorizationgrant-type=authorization_code
spring.security.oauth2.client.provider.keycloak.issuer-uri=http://localhost:8080/realms/formation-realm
spring.security.oauth2.client.provider.keycloak.user-nameattribute=preferred_username