server.port=8083
spring.application.name=demo
spring.batch.job.enabled=false

spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.url=jdbc:h2:mem:dbduplicata
spring.datasource.username=sa
spring.datasource.password=sa

spring.h2.console.enabled=true
spring.batch.jdbc.initialize-schema=always