services:
  elasticsearch:
    image: elasticsearch:8.11.3
    container_name: duplicata_elastic_container
    ports:
    - 9200:9200
    - 9300:9300
    environment:
      - discovery.type=single-node
      - cluster.name=duplicata_cluster
      - xpack.security.enabled=false