spring.application.name=spring-security-form-login-demo
server.port=8080

# Pour voir les décisions de Spring Security dans la console pendant la formation.
logging.level.org.springframework.security=INFO
