management.endpoints.web.exposure.include=*
management.endpoint.health.show-details=always

# H2 DB
spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.hibernate.ddl-auto=update
spring.h2.console.enabled=true

# Elasticsearch
spring.elasticsearch.uris=http://localhost:9200

# Cache
spring.cache.type=simple

# Valeur metier : temps moyen de lecture (en minutes)
bibliotheque.reading.avg-time=120
