spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.hibernate.ddl-auto=update
spring.h2.console.enabled=true

spring.elasticsearch.uris=http://localhost:9200

spring.cache.type=simple

spring.profiles.active=dev

bibliotheque.reading.avg-time=120
