
# Exemple de config pour PostgreSQL + Elasticsearch pour prod
spring.datasource.url=jdbc:postgresql://localhost:5432/bibliotheque
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.jpa.hibernate.ddl-auto=update

# Elasticsearch
spring.elasticsearch.uris=http://localhost:9200

# Cache Caffeine (ou Redis possible)
spring.cache.type=caffeine

# Profil actif
spring.profiles.active=prod

# Valeur métier : temps moyen de lecture (en minutes)
bibliotheque.reading.avg-time=120
