spring.application.name=1_init

server.port=8081
server.forward-headers-strategy=FRAMEWORK
spring.security.oauth2.client.provider.external.issuer-uri=http://localhost:8080/realms/external
spring.security.oauth2.client.registration.external.provider=external
spring.security.oauth2.client.registration.external.client-name=external-client
spring.security.oauth2.client.registration.external.client-id=external-client
spring.security.oauth2.client.registration.external.client-secret=ugQilmk2fmG47WaJuC3SYU91dQ5rTepp
spring.security.oauth2.client.registration.external.scope=openid,offline_access,profile
spring.security.oauth2.client.registration.external.authorization-grant-type=authorization_code

spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.url=jdbc:h2:mem:dbduplicata
spring.datasource.username=sa
spring.datasource.password=sa

spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.show-sql=true
#spring.jpa.properties.hibernate.format_sql=true
spring.jpa.hibernate.ddl-auto=create

spring.h2.console.enabled=true

spring.data.elasticsearch.repositories.enabled=true
spring.elasticsearch.uris=localhost:9200

spring.batch.job.enabled=false
spring.batch.jdbc.initialize-schema=always

management.endpoints.web.exposure.include=*
management.endpoint.health.show-details=always


spring.jpa.defer-datasource-initialization=true