server:
  port: 8080

spring:
  application:
    name: spring-security-oauth2-github-demo
  security:
    oauth2:
      client:
        registration:
          github:
            client-id: Ov23liXkbVtLBskimB0j
            client-secret: 3212f8a3f610133c4392492963c1a63d9c0f8e24
            scope:
              - read:user
              - user:email

logging:
  level:
    org.springframework.security: INFO
