spring.application.name=tp5-security-oauth2-github
server.port=8080

# Ne jamais versionner de vrai secret dans le projet.
# Eclipse : Run Configurations > Environment, ajouter GITHUB_CLIENT_ID et GITHUB_CLIENT_SECRET.
spring.security.oauth2.client.registration.github.client-id=Ov23liXkbVtLBskimB0j
spring.security.oauth2.client.registration.github.client-secret=3212f8a3f610133c4392492963c1a63d9c0f8e24
spring.security.oauth2.client.registration.github.scope=read:user,user:email

spring.thymeleaf.cache=false
